name: Build and Push Using Shared Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        version:
          - '1.8'
          - '2.4'

    uses: nstwfdev/docker-ci/.github/workflows/build.yaml@main
    with:
      version: ${{ matrix.version }}
      docker_image_path: nstwf/${{ github.event.repository.name }}
      image_version_prefix: 'example_prefix-'
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_build_token: ${{ secrets.DOCKER_BUILD_TOKEN }}