name: Build images and push it to registries

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_PATH: nstwf/hello-world
      GHCR_IMAGE_PATH: ghcr.io/nstwf-docker/hello-world
      IMAGE_VERSION_PREFIX: 'hw-'

    strategy:
      matrix:
        version: ['1.9']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_BUILD_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          build-args: |
            VERSION=${{ matrix.VERSION }}
          tags: |
            ${{ env.DOCKER_IMAGE_PATH }}:${{ env.IMAGE_VERSION_PREFIX }}${{ matrix.VERSION }},
            ${{ env.GHCR_IMAGE_PATH }}:${{ env.IMAGE_VERSION_PREFIX }}${{ matrix.VERSION }}
