name: Build and Push Using Shared Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-push:
    if: github.event_name != 'pull_request'

    strategy:
      matrix:
        version:
          - '1.8'
          - '2.4'

    uses: nstwfdev/docker-ci/.github/workflows/docker-build-push-pr.yaml@main
    with:
      image_version: ${{ matrix.version }}
      dockerhub_image: nstwf/${{ github.event.repository.name }}
      docker_extra_build_args: |
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}

  build-push-pr:
    if: github.event_name == 'pull_request'

    strategy:
      matrix:
        version:
          - '1.8'
          - '2.4'

    uses: nstwfdev/docker-ci/.github/workflows/docker-build-push-pr.yaml@main
    with:
      image_version: ${{ matrix.version }}
      dockerhub_image: nstwf/${{ github.event.repository.name }}
      docker_extra_build_args: |
        HW_VERSION= ${{ matrix.version }}
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
      ghcr_username: ${{ github.actor }}
      ghcr_password: ${{ secrets.GHCR_PASSWORD }}